<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Ms_branch_model extends CI_Model
{

    public $table = 'ms_branch';
    public $id = 'branch_code';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('branch_code', $q);
	$this->db->or_like('branch_id', $q);
	$this->db->or_like('head_office_code', $q);
	$this->db->or_like('default_warehouse', $q);
	$this->db->or_like('region_code', $q);
	$this->db->or_like('city_code', $q);
	$this->db->or_like('branch_name', $q);
	$this->db->or_like('branch_address', $q);
	$this->db->or_like('branch_phone', $q);
	$this->db->or_like('branch_contact_person', $q);
	$this->db->or_like('default_currency', $q);
	$this->db->or_like('tax_branch_name', $q);
	$this->db->or_like('tax_branch_address', $q);
	$this->db->or_like('tax_form_serial_number', $q);
	$this->db->or_like('npwp', $q);
	$this->db->or_like('taxable_company_no', $q);
	$this->db->or_like('taxable_company_date', $q);
	$this->db->or_like('labor_type', $q);
	$this->db->or_like('klu_spt', $q);
	$this->db->or_like('input_datetime', $q);
	$this->db->or_like('input_username', $q);
	$this->db->or_like('active', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('branch_code', $q);
	$this->db->or_like('branch_id', $q);
	$this->db->or_like('head_office_code', $q);
	$this->db->or_like('default_warehouse', $q);
	$this->db->or_like('region_code', $q);
	$this->db->or_like('city_code', $q);
	$this->db->or_like('branch_name', $q);
	$this->db->or_like('branch_address', $q);
	$this->db->or_like('branch_phone', $q);
	$this->db->or_like('branch_contact_person', $q);
	$this->db->or_like('default_currency', $q);
	$this->db->or_like('tax_branch_name', $q);
	$this->db->or_like('tax_branch_address', $q);
	$this->db->or_like('tax_form_serial_number', $q);
	$this->db->or_like('npwp', $q);
	$this->db->or_like('taxable_company_no', $q);
	$this->db->or_like('taxable_company_date', $q);
	$this->db->or_like('labor_type', $q);
	$this->db->or_like('klu_spt', $q);
	$this->db->or_like('input_datetime', $q);
	$this->db->or_like('input_username', $q);
	$this->db->or_like('active', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Ms_branch_model.php */
/* Location: ./application/models/Ms_branch_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-09 07:24:47 */
/* http://harviacode.com */